
# OpenRat CMS Configuration
#

login:
  motd: "${env:CMS_MOTD}"

database-default:
  default-id:  db


database:
  db:
    enabled    :  true                 #  set this to 'true' for using this connection
    dsn        :  "${env:DB_TYPE}:host=${env:DB_HOST}; dbname=${env:DB_NAME}"
    description:  "PDO"
    name       :  "PRO"
    type       :  pdo
    user       :  ${env:DB_USER}
    password   :  ${env:DB_PASS}
    base64     :  true                 #  store binary as BASE64 (in postgresql 7.x set this to 'true')
    prefix     :  cms_
    suffix     :  _or
    persistent :  yes                   #  use persistent connections (try this, it's faster)
    charset    :  UTF-8
    cmd        :  ""
    prepare    :  true
    transaction:  true


production: true

application:
	name: "${env:CMS_NAME}"
	operator: "${env:CMS_OPERATOR}"