
# OpenRat CMS configuration - Minimal settings
# Change this file or create 'config-<hostname>.yml'.

database:
  db:
    enabled : false        # remove this line or set the value to 'true' to enable this database
    user    : dbuser       # user
    password: dbpass       # password
    database: cms          # database name

include:
  - ./config/config-${http:host}.yml

# There are a lot of more configuration settings available, see file 'config-all-example.yml' ...
